-- Categories
INSERT INTO categories (name, slug) VALUES
('Jewelry', 'jewelry'),
('Hair Care', 'hair-care'),
('Fragrances', 'fragrances'),
('Skin Care', 'skin-care'),
('Accessories', 'accessories'),
('Grooming Tools', 'grooming-tools');

-- Products
INSERT INTO shop_product
(category_id, name, slug, description, price, stock, available, created_at)
VALUES
(1, 'Classic Silver Necklace', 'classic-silver-necklace', 'Elegant unisex silver necklace, perfect for any occasion.', 59.99, 42, 1, CURRENT_TIMESTAMP),
(1, 'Minimalist Gold Bracelet', 'minimalist-gold-bracelet', 'Sleek gold bracelet designed for everyday wear.', 45.00, 38, 1, CURRENT_TIMESTAMP),
(1, 'Beaded Gemstone Anklet', 'beaded-gemstone-anklet', 'Colorful anklet made with natural gemstones.', 22.50, 55, 1, CURRENT_TIMESTAMP),
(1, 'Adjustable Leather Wristband', 'adjustable-leather-wristband', 'Handcrafted leather wristband with adjustable fit.', 18.99, 60, 1, CURRENT_TIMESTAMP),
(1, 'Pearl Stud Earrings', 'pearl-stud-earrings', 'Classic pearl earrings with hypoallergenic posts.', 35.00, 47, 1, CURRENT_TIMESTAMP),
(1, 'Onyx Signet Ring', 'onyx-signet-ring', 'Chic onyx ring with a modern signet design.', 40.00, 25, 1, CURRENT_TIMESTAMP),
(1, 'Engraved Cuff Bracelet', 'engraved-cuff-bracelet', 'Customizable cuff bracelet with room for engraving.', 55.00, 30, 1, CURRENT_TIMESTAMP),
(1, 'Stainless Steel Chain', 'stainless-steel-chain', 'Durable chain necklace suitable for all styles.', 27.50, 61, 1, CURRENT_TIMESTAMP),
(1, 'Crystal Drop Pendant', 'crystal-drop-pendant', 'Elegant crystal pendant on a fine chain.', 32.00, 49, 1, CURRENT_TIMESTAMP),
(1, 'Infinity Knot Brooch', 'infinity-knot-brooch', 'Symbolic infinity knot brooch for jackets or scarves.', 16.75, 36, 1, CURRENT_TIMESTAMP),
(2, 'Argan Oil Hair Serum', 'argan-oil-hair-serum', 'Nourishing argan oil serum for soft, shiny hair.', 19.99, 70, 1, CURRENT_TIMESTAMP),
(2, 'Volumizing Mousse', 'volumizing-mousse', 'Lightweight mousse for fuller, thicker-looking hair.', 13.50, 50, 1, CURRENT_TIMESTAMP),
(2, 'Matte Hair Clay', 'matte-hair-clay', 'Strong hold clay for natural, matte hairstyles.', 17.00, 44, 1, CURRENT_TIMESTAMP),
(2, 'Moisturizing Shampoo', 'moisturizing-shampoo', 'Hydrating shampoo for all hair types.', 12.49, 67, 1, CURRENT_TIMESTAMP),
(2, 'Repair & Protect Conditioner', 'repair-protect-conditioner', 'Conditioner that strengthens and repairs damaged hair.', 14.00, 52, 1, CURRENT_TIMESTAMP),
(2, 'Leave-In Detangler', 'leave-in-detangler', 'Quick detangler spray for easy combing.', 11.99, 60, 1, CURRENT_TIMESTAMP),
(2, 'Texturizing Sea Salt Spray', 'texturizing-sea-salt-spray', 'Gives hair a beachy, textured look.', 15.00, 40, 1, CURRENT_TIMESTAMP),
(2, 'Anti-Frizz Smoothing Cream', 'anti-frizz-smoothing-cream', 'Controls frizz and flyaways for sleek styles.', 13.99, 55, 1, CURRENT_TIMESTAMP),
(2, 'Curl Defining Gel', 'curl-defining-gel', 'Defines and holds curls without crunch.', 14.50, 29, 1, CURRENT_TIMESTAMP),
(2, 'Scalp Revive Tonic', 'scalp-revive-tonic', 'Soothes and refreshes the scalp.', 16.75, 33, 1, CURRENT_TIMESTAMP),
(3, 'Fresh Citrus Cologne', 'fresh-citrus-cologne', 'Invigorating citrus scent for a fresh start.', 28.00, 57, 1, CURRENT_TIMESTAMP),
(3, 'Woody Musk Perfume', 'woody-musk-perfume', 'Earthy fragrance with woody and musk notes.', 32.50, 46, 1, CURRENT_TIMESTAMP),
(3, 'Ocean Breeze Eau de Toilette', 'ocean-breeze-eau-de-toilette', 'Clean scent reminiscent of the sea.', 24.00, 38, 1, CURRENT_TIMESTAMP),
(3, 'Amber Spice Roll-On', 'amber-spice-roll-on', 'Warm amber and spice fragrance, convenient roll-on.', 18.00, 65, 1, CURRENT_TIMESTAMP),
(3, 'Green Tea Mist', 'green-tea-mist', 'Refreshing mist with green tea essence.', 20.00, 50, 1, CURRENT_TIMESTAMP),
(3, 'Herbal Citrus Body Spray', 'herbal-citrus-body-spray', 'Herbal and citrus notes for all-day freshness.', 16.99, 55, 1, CURRENT_TIMESTAMP),
(3, 'Sandalwood Solid Perfume', 'sandalwood-solid-perfume', 'Solid perfume with calming sandalwood aroma.', 11.50, 32, 1, CURRENT_TIMESTAMP),
(3, 'Vanilla Oud Essence', 'vanilla-oud-essence', 'Exotic blend of vanilla and oud.', 34.00, 29, 1, CURRENT_TIMESTAMP),
(3, 'Urban Night Parfum', 'urban-night-parfum', 'Deep, complex fragrance for evenings out.', 36.99, 41, 1, CURRENT_TIMESTAMP),
(3, 'White Blossom Splash', 'white-blossom-splash', 'Light floral splash for everyday use.', 14.99, 50, 1, CURRENT_TIMESTAMP),
(4, 'Hydrating Gel Moisturizer', 'hydrating-gel-moisturizer', 'Oil-free gel moisturizer for radiant skin.', 19.50, 44, 1, CURRENT_TIMESTAMP),
(4, 'Vitamin C Face Serum', 'vitamin-c-face-serum', 'Brightening serum with stabilized vitamin C.', 23.00, 36, 1, CURRENT_TIMESTAMP),
(4, 'SPF 30 Daily Sunscreen', 'spf-30-daily-sunscreen', 'Lightweight sunscreen for all-day protection.', 17.99, 60, 1, CURRENT_TIMESTAMP),
(4, 'Revitalizing Night Cream', 'revitalizing-night-cream', 'Rich night cream for skin recovery.', 21.50, 28, 1, CURRENT_TIMESTAMP),
(4, 'Soothing Aloe Vera Gel', 'soothing-aloe-vera-gel', 'Multi-use aloe vera gel for instant relief.', 12.00, 39, 1, CURRENT_TIMESTAMP),
(4, 'Charcoal Detox Mask', 'charcoal-detox-mask', 'Purifying mask with activated charcoal.', 14.75, 47, 1, CURRENT_TIMESTAMP),
(4, 'Exfoliating Scrub', 'exfoliating-scrub', 'Gentle exfoliator for smoother skin.', 13.49, 52, 1, CURRENT_TIMESTAMP),
(4, 'Hydra Repair Eye Cream', 'hydra-repair-eye-cream', 'Reduces dark circles and puffiness.', 22.00, 24, 1, CURRENT_TIMESTAMP),
(4, 'Balancing Toner', 'balancing-toner', 'Alcohol-free toner for balanced skin.', 10.99, 35, 1, CURRENT_TIMESTAMP),
(4, 'Ultra Shea Hand Cream', 'ultra-shea-hand-cream', 'Deeply moisturizing shea butter hand cream.', 9.99, 58, 1, CURRENT_TIMESTAMP),
(5, 'Patterned Silk Scarf', 'patterned-silk-scarf', 'Luxurious silk scarf with modern patterns.', 29.00, 36, 1, CURRENT_TIMESTAMP),
(5, 'Reversible Canvas Tote', 'reversible-canvas-tote', 'Sturdy tote bag, reversible design.', 24.99, 45, 1, CURRENT_TIMESTAMP),
(5, 'Bamboo Sunglasses', 'bamboo-sunglasses', 'Eco-friendly sunglasses with bamboo frames.', 31.50, 40, 1, CURRENT_TIMESTAMP),
(5, 'Classic Knit Beanie', 'classic-knit-beanie', 'Warm knit beanie, fits all head sizes.', 13.00, 60, 1, CURRENT_TIMESTAMP),
(5, 'Chunky Keychain', 'chunky-keychain', 'Trendy unisex keychain with chunky links.', 8.49, 70, 1, CURRENT_TIMESTAMP),
(5, 'Adjustable Bucket Hat', 'adjustable-bucket-hat', 'Casual bucket hat with adjustable strap.', 16.00, 55, 1, CURRENT_TIMESTAMP),
(5, 'Minimalist Card Holder', 'minimalist-card-holder', 'Slim card holder for essentials.', 11.99, 64, 1, CURRENT_TIMESTAMP),
(5, 'Stainless Steel Water Bottle', 'stainless-steel-water-bottle', 'Insulated bottle, keeps drinks hot or cold.', 20.00, 35, 1, CURRENT_TIMESTAMP),
(5, 'Portable Compact Mirror', 'portable-compact-mirror', 'Handy mirror for touch-ups on the go.', 7.99, 77, 1, CURRENT_TIMESTAMP),
(5, 'Embroidered Patch Set', 'embroidered-patch-set', 'Set of fun, iron-on patches.', 6.50, 82, 1, CURRENT_TIMESTAMP),
(5, 'Professional Hair Clippers', 'professional-hair-clippers', 'Rechargeable clippers for precise haircuts.', 49.99, 20, 1, CURRENT_TIMESTAMP),
(5, 'Multi-Use Nail Kit', 'multi-use-nail-kit', 'Complete kit for nail care and grooming.', 18.95, 44, 1, CURRENT_TIMESTAMP),
(5, 'Detangling Brush', 'detangling-brush', 'Flexible bristles for easy detangling.', 12.25, 69, 1, CURRENT_TIMESTAMP),
(5, 'Eyebrow Grooming Scissors', 'eyebrow-grooming-scissors', 'Precision scissors for eyebrow shaping.', 9.75, 62, 1, CURRENT_TIMESTAMP),
(5, 'Double-Sided Comb', 'double-sided-comb', 'Versatile comb with fine and wide teeth.', 5.99, 58, 1, CURRENT_TIMESTAMP),
(5, 'Silicone Face Cleansing Brush', 'silicone-face-cleansing-brush', 'Soft silicone brush for deep facial cleansing.', 14.50, 53, 1, CURRENT_TIMESTAMP),
(5, 'Stainless Steel Tweezers', 'stainless-steel-tweezers', 'Precision tweezers for grooming needs.', 7.50, 80, 1, CURRENT_TIMESTAMP),
(5, 'Beard & Mustache Trimmer', 'beard-mustache-trimmer', 'Cordless trimmer for beards and mustaches.', 32.00, 41, 1, CURRENT_TIMESTAMP),
(5, 'Personal Care Travel Set', 'personal-care-travel-set', 'Travel-size grooming essentials in a pouch.', 21.00, 38, 1, CURRENT_TIMESTAMP),
(5, 'Electric Callus Remover', 'electric-callus-remover', 'Removes rough skin from feet quickly.', 22.75, 66, 1, CURRENT_TIMESTAMP);