# Generated by Django 5.2 on 2025-04-21 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_option_alter_category_image_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionvalue',
            name='option',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='options',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='OptionValue',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
